apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: webapp
          image: 158522655848.dkr.ecr.us-east-1.amazonaws.com/web-app-repo:webapp-v1
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql.assignment2.svc.cluster.local"
            - name: DBPORT
              value: "3306"