apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql-ns
spec:
  selector:
    app: mysql
  ports:
    - port: 3306            # Port exposed by the Service
      targetPort: 3306       # MySQL container's port
      protocol: TCP
  type: ClusterIP            # Internal access only
  
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend