apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 158522655848.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:mysql-v1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword" 
