apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: mysql
          image: 158522655848.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:mysql-v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "passwors" # Replace with your secure password