apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  containers:
    - name: webapp
      image: 158522655848.dkr.ecr.us-east-1.amazonaws.com/web-app-repo:webapp-v1
      ports:
        - containerPort: 80
      env:
        - name: DBPORT
          value: "3306"
