apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp-ns
spec:
  selector:
    app: employees
  ports:
    - port: 80               # Port exposed by the Service
      targetPort: 80         # Web app container's port
      nodePort: 30000        # External port for access on each node
      protocol: TCP
  type: NodePort             # Exposes the service externally
